export const API_BASE_URL = '/api/v1'

export const PERMISSIONS = {
  MEMBERS_VIEW: 'members.view',
  MEMBERS_CREATE: 'members.create',
  MEMBERS_EDIT: 'members.edit',
  MEMBERS_DELETE: 'members.delete',
  UNITS_VIEW: 'units.view',
  UNITS_CREATE: 'units.create',
  UNITS_EDIT: 'units.edit',
  UNITS_DELETE: 'units.delete',
  TEAMS_VIEW: 'teams.view',
  TEAMS_CREATE: 'teams.create',
  TEAMS_EDIT: 'teams.edit',
  TEAMS_DELETE: 'teams.delete',
  ASSIGNMENTS_VIEW: 'assignments.view',
  ASSIGNMENTS_CREATE: 'assignments.create',
  ASSIGNMENTS_EDIT: 'assignments.edit',
  ASSIGNMENTS_DELETE: 'assignments.delete',
  RELATIONSHIPS_VIEW: 'relationships.view',
  RELATIONSHIPS_CREATE: 'relationships.create',
  RELATIONSHIPS_EDIT: 'relationships.edit',
  RELATIONSHIPS_DELETE: 'relationships.delete',
  ROLES_VIEW: 'roles.view',
  ROLES_MANAGE: 'roles.manage',
  ASSOCIATIONS_VIEW: 'associations.view',
  ASSOCIATIONS_MANAGE: 'associations.manage',
  UNIT_TYPES_VIEW: 'unit_types.view',
  UNIT_TYPES_MANAGE: 'unit_types.manage',
  DOCUMENT_TYPES_VIEW: 'document_types.view',
  DOCUMENT_TYPES_MANAGE: 'document_types.manage',
  DOCUMENTS_VIEW: 'documents.view',
  DOCUMENTS_CREATE: 'documents.create',
  DOCUMENTS_EDIT: 'documents.edit',
  DOCUMENTS_DELETE: 'documents.delete',
  DOCUMENTS_APPROVE: 'documents.approve',
  COTISATIONS_VIEW: 'cotisations.view',
  COTISATIONS_CREATE: 'cotisations.create',
  COTISATIONS_EDIT: 'cotisations.edit',
  COTISATIONS_DELETE: 'cotisations.delete',
  PROGRESSION_VIEW: 'progression.view',
  PROGRESSION_MANAGE: 'progression.manage',
  AUDIT_VIEW: 'audit.view',
  ADMIN_HARD_DELETE: 'admin.hard_delete',
} as const
