-- Script généré par WEBDEV le 01/06/2026 19:06:50
-- Tables de l'analyse GNDJ_Reinscription_v28.wda
-- pour SQL générique (ANSI 92)

-- Création de la table ADRESSES
CREATE TABLE "ADRESSES" (
    "ADR_RUE" VARCHAR(50) NOT NULL,
    "ADR_SECTEUR" VARCHAR(50) NOT NULL,
    "ADR_VILLE" VARCHAR(50) NOT NULL,
    "ADR_PROVINCE" VARCHAR(50) NOT NULL,
    "ADR_PAYS" VARCHAR(50) NOT NULL,
    "ADR_CODEPOSTAL" VARCHAR(10) NOT NULL,
    "ADR_IMM" VARCHAR(50) NOT NULL,
    "ADR_APPART" VARCHAR(50) NOT NULL,
    "PRECISIONS" LONGVARCHAR NOT NULL,
    "ID_ADRESSES" INTEGER PRIMARY KEY NOT NULL,
    "IDMEMBRES" INTEGER NOT NULL,
    "INTITU_ADRESSE" VARCHAR(50) NOT NULL,
    "CD_TYPE_ADRESSE" VARCHAR(1) NOT NULL);
CREATE INDEX "WDIDX_ADRESSES_IDMEMBRES" ON "ADRESSES" ("IDMEMBRES");
CREATE INDEX "WDIDX_ADRESSES_CD_TYPE_ADRESSE" ON "ADRESSES" ("CD_TYPE_ADRESSE");

-- Création de la table DOCS_ATTACHES
CREATE TABLE "DOCS_ATTACHES" (
    "IDDOCS_ATTACHES" INTEGER PRIMARY KEY NOT NULL,
    "TYPE_DOC" VARCHAR(5) ,
    "REFERENCE" VARCHAR(30) ,
    "NOM_FIC_APPEL" VARCHAR(20) ,
    "ID_ENREG_APPEL" NUMERIC(20,0) ,
    "CHEMIN" VARCHAR(255) ,
    "IMAGE" LONGVARBINARY ,
    "REMARQUES" NTEXT ,
    "APPL_APPEL" VARCHAR(20) ,
    "RESUME" NTEXT ,
    "CONTENU_TEXTE" NTEXT );
CREATE INDEX "WDIDX_DOCS_ATTACHES_CLE_1" ON "DOCS_ATTACHES" ("APPL_APPEL","NOM_FIC_APPEL","ID_ENREG_APPEL");

-- Création de la table EMAILS
CREATE TABLE "EMAILS" (
    "INTITU_EMAIL" VARCHAR(50) NOT NULL,
    "ADR_EMAIL" VARCHAR(50) NOT NULL,
    "STATUT_EMAIL" VARCHAR(1) NOT NULL,
    "ID_EMAIL01" INTEGER PRIMARY KEY NOT NULL,
    "IDMEMBRES" INTEGER NOT NULL,
    "CD_TYPE_EMAIL" VARCHAR(1) NOT NULL,
    "URGENCE" BIT NOT NULL);
CREATE INDEX "WDIDX_EMAILS_IDMEMBRES" ON "EMAILS" ("IDMEMBRES");

-- Création de la table Emails_Reinscriptions
CREATE TABLE "Emails_Reinscriptions" (
    "IDEmails_Reinscriptions" NUMERIC(19,0) PRIMARY KEY NOT NULL,
    "IDReinscription" NUMERIC(19,0) ,
    "Numero_Email" VARCHAR(50) ,
    "Contenu_Email" LONGVARCHAR ,
    "Date_Email" DATE ,
    "IDMEMBRES" NUMERIC(19,0) );
CREATE INDEX "WDIDX_Emails_Reinscriptions_IDReinscription" ON "Emails_Reinscriptions" ("IDReinscription");
CREATE INDEX "WDIDX_Emails_Reinscriptions_IDMEMBRES" ON "Emails_Reinscriptions" ("IDMEMBRES");

-- Création de la table ETATSERVICE
CREATE TABLE "ETATSERVICE" (
    "IDETATSERVICE" INTEGER PRIMARY KEY NOT NULL,
    "DATEDEB" VARCHAR(10) NOT NULL,
    "REMARQUES" LONGVARCHAR NOT NULL,
    "ETATLIEU" VARCHAR(40) NOT NULL,
    "IDMEMBRES" INTEGER NOT NULL,
    "TYPEUNITE" VARCHAR(3) NOT NULL,
    "CODEETAT" VARCHAR(3) NOT NULL,
    "UNITE" VARCHAR(3) NOT NULL,
    "CODEBADGE" VARCHAR(6) NOT NULL);
CREATE INDEX "WDIDX_ETATSERVICE_IDMEMBRES" ON "ETATSERVICE" ("IDMEMBRES");
CREATE INDEX "WDIDX_ETATSERVICE_UNITE" ON "ETATSERVICE" ("UNITE");
CREATE INDEX "WDIDX_ETATSERVICE_TYPEUNITECODEETATBADGE" ON "ETATSERVICE" ("TYPEUNITE","CODEETAT","CODEBADGE");

-- Création de la table Login
CREATE TABLE "Login" (
    "IDLogin" NUMERIC(19,0) PRIMARY KEY NOT NULL,
    "MotDePasse" LONGVARCHAR NOT NULL,
    "Username" VARCHAR(70) NOT NULL,
    "CompteActif" BIT NOT NULL,
    "Nom_Utilisateur" VARCHAR(50) NOT NULL,
    "Tel_Utilisateur" VARCHAR(50) NOT NULL,
    "Type_Utilisateur" VARCHAR(5) NOT NULL,
    "Unite" VARCHAR(50) NOT NULL,
    "ID_Membre" NUMERIC(20,0) NOT NULL,
    "Backup_Email" VARCHAR(70) NOT NULL,
    "AccountDisabled" BIT NOT NULL);
CREATE INDEX "WDIDX_Login_Username" ON "Login" ("Username");
CREATE INDEX "WDIDX_Login_Nom_Utilisateur" ON "Login" ("Nom_Utilisateur");
CREATE INDEX "WDIDX_Login_ID_Membre" ON "Login" ("ID_Membre");

-- Création de la table MEMBRES
CREATE TABLE "MEMBRES" (
    "IDMEMBRES" INTEGER PRIMARY KEY NOT NULL,
    "NOM_25" VARCHAR(25) NOT NULL,
    "PRENOM_25" VARCHAR(25) NOT NULL,
    "PERE_PRENOM_25" VARCHAR(25) NOT NULL,
    "MERE_PRENOM_25" VARCHAR(25) NOT NULL,
    "MERE_NOM_50" VARCHAR(50) NOT NULL,
    "DT_NAISS" DATE NOT NULL,
    "SEXE" VARCHAR(1) NOT NULL,
    "GRP_SANG" VARCHAR(3) NOT NULL,
    "NATIONALITE" VARCHAR(2) NOT NULL,
    "PHOTO" VARCHAR(100) NOT NULL,
    "NUM_CARTE" VARCHAR(10) NOT NULL UNIQUE,
    "MEMB_CLASSE" VARCHAR(4) NOT NULL,
    "MEMB_SECTION" VARCHAR(50) NOT NULL,
    "NOMETPRENOM_51" VARCHAR(51) NOT NULL,
    "PERE_DECEDE" BIT NOT NULL,
    "MERE_DECEDEE" BIT NOT NULL,
    "INSCRIPTION_OK" BIT NOT NULL,
    "PERE_PROF" VARCHAR(50) NOT NULL,
    "MERE_PROF" VARCHAR(50) NOT NULL,
    "MEMB_ECOLE" VARCHAR(50) NOT NULL,
    "MEMB_EXAM" BIT NOT NULL,
    "Parents_SeparesOuDivorces" VARCHAR(1) NOT NULL,
    "AUTOCARISTE" BIT NOT NULL,
    "NAVETTE_SG" BIT NOT NULL,
    "VALIDATION_INFORMATION" BIT NOT NULL,
    "INSTRUMENTS_MUSIQUE" VARCHAR(200) NOT NULL,
    "MEMB_ECOLE_AUTRE" VARCHAR(50) NOT NULL);
CREATE INDEX "WDIDX_MEMBRES_NOMETPRENOM_51" ON "MEMBRES" ("NOMETPRENOM_51");

-- Création de la table Passage
CREATE TABLE "Passage" (
    "IDPassage" NUMERIC(19,0) PRIMARY KEY NOT NULL,
    "IDMEMBRES" INTEGER UNIQUE,
    "IDUNITEFONC" INTEGER UNIQUE,
    "UniteProposee" VARCHAR(5) ,
    "UniteActuelle" VARCHAR(5) ,
    "Remarques" LONGVARCHAR ,
    "UniteFinale" VARCHAR(5) ,
    "UniteTemporaire" VARCHAR(50) );
CREATE INDEX "WDIDX_Passage_UniteProposee" ON "Passage" ("UniteProposee");
CREATE INDEX "WDIDX_Passage_UniteActuelle" ON "Passage" ("UniteActuelle");

-- Création de la table PATEQSIZ
CREATE TABLE "PATEQSIZ" (
    "UNITE" VARCHAR(3) NOT NULL,
    "TOTEM" VARCHAR(50) NOT NULL,
    "ADJECTIF" VARCHAR(20) NOT NULL,
    "COULEUR1" SMALLINT NOT NULL,
    "COULEUR2" SMALLINT NOT NULL);
CREATE INDEX "WDIDX_PATEQSIZ_UNITE" ON "PATEQSIZ" ("UNITE");
CREATE INDEX "WDIDX_PATEQSIZ_COULEUR1" ON "PATEQSIZ" ("COULEUR1");
CREATE INDEX "WDIDX_PATEQSIZ_COULEUR2" ON "PATEQSIZ" ("COULEUR2");
CREATE INDEX "WDIDX_PATEQSIZ_UNITOTEM" ON "PATEQSIZ" ("UNITE","TOTEM");

-- Création de la table Reinscription
CREATE TABLE "Reinscription" (
    "IDReinscription" NUMERIC(19,0) PRIMARY KEY NOT NULL,
    "AUT_Status" VARCHAR(10) ,
    "FM_Status" VARCHAR(10) ,
    "CI_Status" VARCHAR(10) ,
    "IDMEMBRES" NUMERIC(19,0) ,
    "Inscription_OK" BIT ,
    "COT_Status" VARCHAR(10) ,
    "COT_Amount_LBP" NUMERIC(24,6) ,
    "COT_Amount_USD" NUMERIC(24,6) ,
    "Date_Email" DATE ,
    "NumeroRecu" VARCHAR(20) ,
    "NouveauMembre" BIT );
CREATE INDEX "WDIDX_Reinscription_IDMEMBRES" ON "Reinscription" ("IDMEMBRES");

-- Création de la table Sessions_Navigateurs
CREATE TABLE "Sessions_Navigateurs" (
    "IDSessions_Navigateurs" NUMERIC(19,0) PRIMARY KEY NOT NULL,
    "DateHeure_Connexion" TIMESTAMP ,
    "DateHeure_Deconnexion" TIMESTAMP ,
    "Navig_AdresseIP_SelonEnTeteHTTP" VARCHAR(40) ,
    "Navig_AdresseIP_SelonServeurWeb" VARCHAR(40) ,
    "Navig_Nom" VARCHAR(200) ,
    "Navig_Plateforme" VARCHAR(50) ,
    "Navig_Type" VARCHAR(50) ,
    "Navig_Version" VARCHAR(10) ,
    "Navig_VersionComplete" VARCHAR(200) ,
    "Navig_OS" VARCHAR(50) ,
    "Navig_SurMobile" BIT ,
    "IDLogin" NUMERIC(19,0) ,
    "Username" VARCHAR(70) ,
    "Nom_Utilisateur" VARCHAR(50) ,
    "Type_Utilisateur" VARCHAR(5) ,
    "Administrateur" BIT );
CREATE INDEX "WDIDX_Sessions_Navigateurs_IDLogin" ON "Sessions_Navigateurs" ("IDLogin");
CREATE INDEX "WDIDX_Sessions_Navigateurs_Username" ON "Sessions_Navigateurs" ("Username");

-- Création de la table T_BADGES
CREATE TABLE "T_BADGES" (
    "CODEBADGE" VARCHAR(6) NOT NULL,
    "TYPEUNITE" VARCHAR(3) NOT NULL,
    "DESC_30" VARCHAR(30) NOT NULL,
    "CHAMP_VISIBLE" BIT NOT NULL,
    "LISTE_RANG" INTEGER NOT NULL);
CREATE INDEX "WDIDX_T_BADGES_TYPEUNITE" ON "T_BADGES" ("TYPEUNITE");
CREATE INDEX "WDIDX_T_BADGES_TYPEUNITECODEBADGE" ON "T_BADGES" ("TYPEUNITE","CODEBADGE");

-- Création de la table T_ETATS
CREATE TABLE "T_ETATS" (
    "CODEETAT" VARCHAR(3) NOT NULL,
    "TYPEUNITE" VARCHAR(3) NOT NULL,
    "DESC_30" VARCHAR(30) NOT NULL,
    "CHAMP_VISIBLE" BIT NOT NULL,
    "LISTE_RANG" INTEGER NOT NULL);
CREATE INDEX "WDIDX_T_ETATS_TYPEUNITE" ON "T_ETATS" ("TYPEUNITE");
CREATE INDEX "WDIDX_T_ETATS_TYPEUNITECODEETAT" ON "T_ETATS" ("TYPEUNITE","CODEETAT");

-- Création de la table T_FONC
CREATE TABLE "T_FONC" (
    "CODEFONCTION" VARCHAR(4) NOT NULL,
    "NOMFONCTION" VARCHAR(50) NOT NULL,
    "MAITRISE_O_N" BIT NOT NULL,
    "RANG" VARCHAR(2) NOT NULL,
    "FONCT_OFF" VARCHAR(4) NOT NULL,
    "COTISAT_ASSO" FLOAT NOT NULL,
    "TYPEUNITE" VARCHAR(3) NOT NULL,
    "LISTE_RANG" INTEGER NOT NULL,
    "ID_T_FONC" INTEGER PRIMARY KEY NOT NULL);
CREATE INDEX "WDIDX_T_FONC_CODEFONCTION" ON "T_FONC" ("CODEFONCTION");
CREATE INDEX "WDIDX_T_FONC_TYPEUNITE" ON "T_FONC" ("TYPEUNITE");

-- Création de la table T_NATURE_DOCUMENT
CREATE TABLE "T_NATURE_DOCUMENT" (
    "IDT_NATURE_DOCUMENT" INTEGER PRIMARY KEY NOT NULL,
    "DESC_FR_50" VARCHAR(50) ,
    "CD_NATURE_DOCUMENT" VARCHAR(5) UNIQUE,
    "DESC_EN_50" VARCHAR(50) ,
    "DESC_AR_50" VARCHAR(50) );
CREATE INDEX "WDIDX_T_NATURE_DOCUMENT_DESC_FR_50" ON "T_NATURE_DOCUMENT" ("DESC_FR_50");
CREATE INDEX "WDIDX_T_NATURE_DOCUMENT_DESC_EN_50" ON "T_NATURE_DOCUMENT" ("DESC_EN_50");
CREATE INDEX "WDIDX_T_NATURE_DOCUMENT_DESC_AR_50" ON "T_NATURE_DOCUMENT" ("DESC_AR_50");

-- Création de la table T_Parametres
CREATE TABLE "T_Parametres" (
    "IDT_Parametres" INTEGER PRIMARY KEY NOT NULL,
    "CodeParametre" NVARCHAR(50) ,
    "ValeurParametre" NVARCHAR(256) ,
    "CodeSection" NVARCHAR(20) ,
    "Remarques_256" NVARCHAR(256) ,
    "Niveau_Operateur" VARCHAR(1) ,
    "ConfigurationDebutAnnee" BIT );
CREATE INDEX "WDIDX_T_Parametres_CodeSectionCodeParametre" ON "T_Parametres" ("CodeSection","CodeParametre");

-- Création de la table T_PAYS
CREATE TABLE "T_PAYS" (
    "CODE_PAYS" VARCHAR(2) NOT NULL UNIQUE,
    "LIB_FR_50" VARCHAR(50) NOT NULL,
    "LIB_EN_50" VARCHAR(50) NOT NULL,
    "LIB_AR_50" VARCHAR(50) NOT NULL);
CREATE INDEX "WDIDX_T_PAYS_LIB_FR_50" ON "T_PAYS" ("LIB_FR_50");
CREATE INDEX "WDIDX_T_PAYS_LIB_EN_50" ON "T_PAYS" ("LIB_EN_50");
CREATE INDEX "WDIDX_T_PAYS_LIB_AR_50" ON "T_PAYS" ("LIB_AR_50");

-- Création de la table T_TYPE_ADRESSE
CREATE TABLE "T_TYPE_ADRESSE" (
    "IDT_TYPE_ADRESSE" INTEGER PRIMARY KEY NOT NULL,
    "CD_TYPE_ADRESSE" VARCHAR(1) UNIQUE,
    "DESC_FR_50" VARCHAR(50) ,
    "DESC_EN_50" VARCHAR(50) ,
    "DESC_AR_50" VARCHAR(50) );
CREATE INDEX "WDIDX_T_TYPE_ADRESSE_DESC_FR_50" ON "T_TYPE_ADRESSE" ("DESC_FR_50");
CREATE INDEX "WDIDX_T_TYPE_ADRESSE_DESC_EN_50" ON "T_TYPE_ADRESSE" ("DESC_EN_50");
CREATE INDEX "WDIDX_T_TYPE_ADRESSE_DESC_AR_50" ON "T_TYPE_ADRESSE" ("DESC_AR_50");

-- Création de la table T_TYPE_EMAIL
CREATE TABLE "T_TYPE_EMAIL" (
    "IDT_TYPE_EMAIL" INTEGER PRIMARY KEY NOT NULL,
    "CD_TYPE_EMAIL" VARCHAR(1) UNIQUE,
    "DESC_FR_50" VARCHAR(50) ,
    "DESC_EN_50" VARCHAR(50) ,
    "DESC_AR_50" VARCHAR(50) );
CREATE INDEX "WDIDX_T_TYPE_EMAIL_DESC_FR_50" ON "T_TYPE_EMAIL" ("DESC_FR_50");
CREATE INDEX "WDIDX_T_TYPE_EMAIL_DESC_EN_50" ON "T_TYPE_EMAIL" ("DESC_EN_50");
CREATE INDEX "WDIDX_T_TYPE_EMAIL_DESC_AR_50" ON "T_TYPE_EMAIL" ("DESC_AR_50");

-- Création de la table T_TYPE_TELEPHONE
CREATE TABLE "T_TYPE_TELEPHONE" (
    "IDT_TYPE_TELEPHONE" INTEGER PRIMARY KEY NOT NULL,
    "CD_TYPE_TELEPHONE" VARCHAR(2) UNIQUE,
    "DESC_FR_50" VARCHAR(50) ,
    "DESC_EN_50" VARCHAR(50) ,
    "DESC_AR_50" VARCHAR(50) );
CREATE INDEX "WDIDX_T_TYPE_TELEPHONE_DESC_FR_50" ON "T_TYPE_TELEPHONE" ("DESC_FR_50");
CREATE INDEX "WDIDX_T_TYPE_TELEPHONE_DESC_EN_50" ON "T_TYPE_TELEPHONE" ("DESC_EN_50");
CREATE INDEX "WDIDX_T_TYPE_TELEPHONE_DESC_AR_50" ON "T_TYPE_TELEPHONE" ("DESC_AR_50");

-- Création de la table T_UNITES
CREATE TABLE "T_UNITES" (
    "CODEUNITE" VARCHAR(3) NOT NULL UNIQUE,
    "NOMUNITE" VARCHAR(30) NOT NULL,
    "ASSOC" VARCHAR(3) NOT NULL,
    "TROMBINO_L1" VARCHAR(30) NOT NULL,
    "TROMBINO_L2" VARCHAR(30) NOT NULL,
    "TYPEUNITE" VARCHAR(3) NOT NULL,
    "NUM_UNITE" NUMERIC(10,0) NOT NULL,
    "INTITU_DISTRICT" VARCHAR(50) NOT NULL,
    "INTITU_GROUPE" VARCHAR(50) NOT NULL,
    "UNITE_VISIBLE" BIT NOT NULL);
CREATE INDEX "WDIDX_T_UNITES_TYPEUNITE" ON "T_UNITES" ("TYPEUNITE");

-- Création de la table TELEPHONES
CREATE TABLE "TELEPHONES" (
    "INTITU_TEL" VARCHAR(50) NOT NULL,
    "CD_TEL_PAYS" VARCHAR(3) NOT NULL,
    "CD_TEL_REGION" VARCHAR(4) NOT NULL,
    "NUM_TEL" VARCHAR(10) NOT NULL,
    "EXT_TEL" VARCHAR(5) NOT NULL,
    "ID_TELEPH01" INTEGER PRIMARY KEY NOT NULL,
    "IDMEMBRES" INTEGER NOT NULL,
    "CD_TYPE_TELEPHONE" VARCHAR(2) NOT NULL,
    "URGENCE" BIT NOT NULL);
CREATE INDEX "WDIDX_TELEPHONES_IDMEMBRES" ON "TELEPHONES" ("IDMEMBRES");

-- Création de la table UNITEFONC
CREATE TABLE "UNITEFONC" (
    "IDUNITEFONC" INTEGER PRIMARY KEY NOT NULL,
    "UNITE" VARCHAR(3) NOT NULL,
    "FONCTION1" VARCHAR(50) NOT NULL,
    "DATEDEB" VARCHAR(10) NOT NULL,
    "DATEFIN" VARCHAR(10) NOT NULL,
    "REMARQUES" LONGVARCHAR NOT NULL,
    "NUM_CARTE" VARCHAR(10) NOT NULL,
    "IDMEMBRES" INTEGER NOT NULL,
    "ASSOC" VARCHAR(3) NOT NULL,
    "EnCours" BIT NOT NULL,
    "TOTEM" VARCHAR(50) NOT NULL,
    "RANG" VARCHAR(2) NOT NULL);
CREATE INDEX "WDIDX_UNITEFONC_UNITE" ON "UNITEFONC" ("UNITE");
CREATE INDEX "WDIDX_UNITEFONC_IDMEMBRES" ON "UNITEFONC" ("IDMEMBRES");
CREATE INDEX "WDIDX_UNITEFONC_UNITETOTEM" ON "UNITEFONC" ("UNITE","TOTEM");
