// The app's brand mark: the group-logo compass "médaillon" (same artwork as the installed-app icon and the
// favicon, generated by tools/app-icon/build.mjs). A plain <img> of /favicon.svg — the SVG already carries its
// own rounded tile, so callers only size it. ?v=3 matches index.html so a future redesign busts caches together.
import { cn } from '@/lib/utils'

export function BrandMark({ className }: { className?: string }) {
  return <img src="/favicon.svg?v=3" alt="" aria-hidden="true" draggable={false} className={cn('shrink-0 select-none', className)} />
}
