// Camp BP carte: a clean plan of the Collège Notre-Dame de Jamhour grounds (public/camp/carte-jamhour.svg,
// generated by tools/camp-map/build.mjs). Nothing is drawn on it on purpose. "Imprimer" prints only the map
// on one landscape page; "Télécharger" saves the SVG (opens in any browser / Inkscape,
// scales without blur for a big print).
import { Download, Printer } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'

export const CAMP_MAP_URL = '/camp/carte-jamhour.svg'

// Print just the map on a landscape page. The @page rule is added only for this print (a global one would turn
// every other print in the app to landscape) and removed once the print dialog closes.
function printMap() {
  const style = document.createElement('style')
  style.textContent = '@page { size: landscape; margin: 8mm; }'
  document.head.appendChild(style)
  const cleanup = () => { style.remove(); window.removeEventListener('afterprint', cleanup) }
  window.addEventListener('afterprint', cleanup)
  window.print()
}

export function CampMap() {
  return (
    <Card>
      <CardContent className="space-y-3 pt-4">
        <div className="no-print flex flex-wrap items-center gap-2">
          <p className="font-medium">Carte du collège</p>
          <div className="ml-auto flex gap-2">
            <Button size="sm" variant="outline" onClick={printMap}>
              <Printer className="mr-1 h-4 w-4" />Imprimer
            </Button>
            <Button size="sm" variant="outline" asChild>
              <a href={CAMP_MAP_URL} download="Carte du college - Jamhour.svg"><Download className="mr-1 h-4 w-4" />Télécharger</a>
            </Button>
          </div>
        </div>
        <div className="print-area camp-map-print overflow-hidden rounded-lg border bg-white">
          <img src={CAMP_MAP_URL} alt="Carte du Collège Notre-Dame de Jamhour" className="block h-auto w-full" />
        </div>
      </CardContent>
    </Card>
  )
}
